resources:
- ../../base
namePrefix: silvapp-

patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: mywebapp
- path: name.yaml
  target:
    kind: Deployment
    name: mywebapp

    
configMapGenerator:
- name: mykustom-map
  env: config.properties
