resources:
- ../../base

patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: new-app-name
- path: name.yaml
  target:
    kind: Deployment
    name: new-app-name

configMapGenerator:
- name: mykustom-map
  env: config.properties
