resources:
- ../../base

patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: webapp
- path: name.yaml
  target:
    kind: Deployment
    name: webapp
    
configMapGenerator:
- name: mykustom-map
  env: config.properties
